### ISSUE TITLE
Examine Github events deprecation and how it might affect the app

### ISSUE THREAD

**Issue by jessetab** [tableau-mkt/github-release-bot#5]
Per the email below, Github is deprecating two events `integration_installation` and `integration_installation_repositories`. 99% sure that the  Release Bot Github App we use for www7 deployments do not rely on these events. 

The action item for this ticket is to confirm that the event deprecation will not affect the app functionality. Once confirmed, this ticket can be closed. 

> Hi @tableau-mkt Admin,
> 
> We're contacting you regarding upcoming changes to GitHub Apps owned by your organization:
> - tableau-mkt-github-release-bot
> 
> We no longer support two events which your GitHub Apps may rely on, "integration_installation" and "integration_installation_repositories".
> 
> These events can be replaced with the "installation" and "installation_repositories" events respectively.
> 
> The "integration_installation" and "integration_installation_repositories" events will be removed after October 1st, 2020.
> 
> Please visit https://developer.github.com/changes/2020-04-15-replacing-the-installation-and-installation-repositories-events for more information about suggested changes, brownouts, and removal dates.
> 
> Thanks,
> The GitHub Team

**Comment by mattwithrow** [comment]
@jessetab Can you please provide some insight on this one?

**Comment by jessetab** [comment]
@mattwithrow I added some more details to the ticket body, there's likely nothing to be done here. This is more of a confirm there is nothing to be done kind of ticket. Just to be safe. 

> Per the email below, Github is deprecating two events `integration_installation` and `integration_installation_repositories`. 99% sure that the  Release Bot Github App we use for www7 deployments do not rely on these events. 

>The action item for this ticket is to confirm that the event deprecation will not affect the app functionality. Once confirmed, this ticket can be closed.

**Comment by jessetab** [comment]
@mattwithrow I'll assign it to myself, it's a quick check.

**Comment by jessetab** [comment]
no longer valid.
